### ISSUE TITLE
PI5 issues

### ISSUE THREAD

**Issue by foxale08** [CrimeIsDown/sdrtrunk-docker#1]
Just FYI, I had to modify the docker compose file to include the following to allow this to function on a PI 5, additionally this is incompatible with the new 16K kernel and I had to downgrade to kernel8.img (from kernel_2712.img.)
```

services:
  sdrtrunk:
    build:
      context: .
      args:
        TARGETPLATFORM: "linux/arm64" <- docker compose couldn't detect ARCH, may be related to kernel
    container_name: sdrtrunk
    restart: always
    ports:
      - "${CUSTOM_PORT:-3000}:${CUSTOM_PORT:-3000}"
      - "${CUSTOM_HTTPS_PORT:-3001}:${CUSTOM_HTTPS_PORT:-3001}"
    environment:
      # Use the same user and group id as the host user
      - PUID=1000
      - PGID=1000
      - CUSTOM_PORT
      - CUSTOM_HTTPS_PORT
    devices:
      # Mount the host's USB devices
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      # Mount the host's shared memory for SDRPlay
      - /dev/shm:/dev/shm
      # Needed for udev to work properly
      - /run/udev/data:/run/udev/data
      # Mount the host's SDRTrunk configuration and Java configuration
      - /opt/docker/sdrtrunk/config:/config/SDRTrunk:rw <-changed to rw for JMBE library
      - ~/.java:/config/.java
      - /usr/local/lib:/usr/local/lib <--added after installing sdrplay api
      - /opt/docker/sdrtrunk/nyginxlog:/var/log/nginx:rw <- added 
      - /opt/sdrplay_api:/opt/sdrplay_api <-added after installing sdrplay api
```
